repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key        # Prevent committing private keys
      - id: check-added-large-files   # Prevent large files
      - id: check-yaml                # Validate YAML files
      - id: check-toml                # Validate TOML files
      - id: check-merge-conflict      # Check for merge conflicts

  # Only keep Bandit for security
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.7'
    hooks:
      - id: bandit
        exclude: 'tests/.*$'
        args: ['--severity-level', 'high'] 