repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key        # Prevent committing private keys (critical for SOC2/HIPAA)
      - id: check-added-large-files   # Prevent large files that might contain sensitive data
      - id: check-yaml                # Validate YAML files
      - id: check-toml                # Validate TOML files
      - id: check-merge-conflict      # Check for merge conflicts
      # Removed less critical checks to speed up the process

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--select=S,B,I,E,F, --fix]  # Focus on security (S) and bugs (B)
        files: \.py$

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        files: ^src/.*\.py$
        additional_dependencies: ["bandit[toml]"]

  # Local hooks for custom checks
  - repo: local
    hooks:
      - id: check-pii-data
        name: Check for PII data patterns in source code
        entry: grep -r -E "(password|secret|key|token|ssn|credit.?card|social.?security)" --include="*.py" --exclude-dir=".git" --exclude-dir="__pycache__" --exclude-dir=".venv" --exclude-dir="tests" --exclude-dir="examples" src/
        language: system
        pass_filenames: false
        always_run: true
        # This will fail if it finds any of these patterns, helping with GDPR/HIPAA compliance
        
      - id: safety-check
        name: Safety dependency check
        entry: safety check
        language: system
        pass_filenames: false
        always_run: true 