site_name: Cylestio Monitor
site_description: Monitoring and security for AI agents
site_author: Cylestio
site_url: https://docs.cylestio.com
copyright: Copyright &copy; 2024 Cylestio

# Ensure GitHub Pages doesn't use Jekyll
# Note: The .nojekyll file is created in the GitHub Actions workflow

theme:
  name: material
  icon:
    logo: material/shield-check
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
  # Remove "Made with Material for MkDocs" footer
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

# GitHub Pages Configuration
use_directory_urls: true

# Explicitly set the docs_dir to ensure correct file paths
docs_dir: docs

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Monitoring AI Agents: user-guide/monitoring-agents.md
    - Framework Support:
      - Overview: user-guide/frameworks/index.md
      - MCP Integration: user-guide/frameworks/mcp.md
    - Security Features: user-guide/security-features.md
    - Logging Options: user-guide/logging-options.md
  - SDK Reference:
    - Overview: sdk-reference/overview.md
    - Monitor Module: sdk-reference/monitor.md
    - Events System: sdk-reference/events.md
    - Database: sdk-reference/database.md
  - Security:
    - Compliance Reports: security/compliance-reports.md
    - Security Best Practices: security/best-practices.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - FAQs: troubleshooting/faqs.md
  - Advanced Topics:
    - Monitoring Channels: monitoring_channels.md
    - Custom Integrations: advanced-topics/custom-integrations.md
    - Performance: advanced-topics/performance.md
    - Integration Patterns: best-practices/integration-patterns.md
  - Best Practices:
    - Security: best-practices/security.md
    - Monitoring: best-practices/monitoring.md
  - Development:
    - Contributing: development/contributing.md
    - Changelog: development/changelog.md
  - Database Reference: database.md 