site_name: Cylestio Monitor
site_description: Security and Monitoring for AI Agents
site_author: Cylestio
site_url: https://docs.cylestio.com/
copyright: Copyright &copy; 2024 Cylestio

# Ensure GitHub Pages doesn't use Jekyll
# Note: The .nojekyll file is created in the GitHub Actions workflow

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: material/shield-check
  favicon: assets/favicon.ico
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tooltips
  # Remove "Made with Material for MkDocs" footer
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
      title: On this page
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - tags
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: google
            show_root_heading: true
            show_category_heading: true
            members_order: source

# GitHub Pages Configuration
use_directory_urls: true

# Explicitly set the docs_dir to ensure correct file paths
docs_dir: docs

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Monitoring Agents:
      - Basic Monitoring: user-guide/monitoring-agents.md
      - LLM Monitoring: user-guide/monitoring-llm.md
      - MCP Integration: user-guide/monitoring-mcp.md
    - Security Features: user-guide/security-features.md
    - Dashboard Integration: user-guide/dashboard.md
  - SDK Reference:
    - Overview: sdk-reference/overview.md
    - Monitor Module: sdk-reference/monitor.md
    - Events:
      - Overview: sdk-reference/events-listener.md
      - Event Processing: sdk-reference/events-processor.md
    - Database: api-reference/database.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - FAQs: troubleshooting/faqs.md
  - Advanced Topics:
    - Monitoring Channels: monitoring_channels.md
    - Custom Integrations: advanced-topics/custom-integrations.md
    - Performance: advanced-topics/performance.md
    - Integration Patterns: best-practices/integration-patterns.md
  - Best Practices:
    - Security: best-practices/security.md
    - Monitoring: best-practices/monitoring.md
  - Development:
    - Contributing: development/contributing.md
    - Changelog: development/changelog.md
  - Database Reference: database.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cylestio/cylestio-monitor
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cylestio-monitor/
  version:
    provider: mike 