name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
        fetch-depth: 0
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Clean Python cache
      run: |
        echo "Cleaning Python cache files..."
        find . -type d -name __pycache__ -exec rm -rf {} +
        find . -type f -name "*.pyc" -delete
        find . -type f -name "*.pyo" -delete
        find . -type f -name "*.pyd" -delete
        
        # Delete pytest cache directories and explicit nodeids file
        find . -type d -name ".pytest_cache" -exec rm -rf {} +
        find . -name "nodeids" -delete
        find . -name "lastfailed" -delete
        
        find . -type d -name ".coverage" -exec rm -rf {} +
        find . -type d -name ".ruff_cache" -exec rm -rf {} +
        find . -type d -name ".mypy_cache" -exec rm -rf {} +
        
        # List test files to verify deleted files are gone
        echo "Current test files in repository:"
        find tests -name "test_*.py" | sort
        
        echo "Cache cleanup complete"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build pytest pytest-cov pytest-asyncio
        
        # Install the package with all dependencies
        python -m pip install -e ".[dev,test]"
    
    - name: Regenerate pytest cache
      run: |
        # Force collection of tests without actually running them
        echo "Regenerating pytest cache with current test files only..."
        python -m pytest --collect-only -v || true
        
    - name: Verify dependencies
      run: |
        # Verify installation of critical dependencies
        echo "Checking installed packages..."
        pip list
        python --version
        
    - name: Run linters and formatters
      run: |
        pip install black isort mypy ruff
        black --check .
        isort --check-only .
        mypy src tests || echo "Mypy check complete with issues"
        ruff check .
      continue-on-error: true
        
    - name: Security checks
      run: |
        echo "Skipping security checks temporarily"
      continue-on-error: true
        
    - name: Run tests with coverage
      run: |
        # Run tests directly with pytest
        python -m pytest -v --cov=src --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
      continue-on-error: true

  integration-tests:
    needs: test
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Clean Python cache
      run: |
        echo "Cleaning Python cache files..."
        find . -type d -name __pycache__ -exec rm -rf {} +
        find . -type f -name "*.pyc" -delete
        find . -type f -name "*.pyo" -delete
        find . -type f -name "*.pyd" -delete
        
        # Delete pytest cache directories and explicit nodeids file
        find . -type d -name ".pytest_cache" -exec rm -rf {} +
        find . -name "nodeids" -delete
        find . -name "lastfailed" -delete
        
        find . -type d -name ".coverage" -exec rm -rf {} +
        
        # List test files to verify deleted files are gone
        echo "Current test files in repository:"
        find tests -name "test_*.py" | sort
        
        echo "Cache cleanup complete"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,test]"
        pip install pytest-asyncio
        
    - name: Regenerate pytest cache
      run: |
        # Force collection of tests without actually running them
        echo "Regenerating pytest cache with current test files only..."
        python -m pytest --collect-only -m "integration" -v || true
        
    - name: Run integration tests
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        python -m pytest -v -m "integration"
      continue-on-error: true

  security-scan:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'cylestio-monitor'
        path: '.'
        format: 'HTML'
      continue-on-error: true
        
    - name: Upload dependency check report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: reports

  deploy:
    needs: [test, integration-tests, security-scan]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: python -m build
      
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine check dist/*
        twine upload dist/* 