name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/deploy_docs.yml'
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Configure Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Deploy documentation to gh-pages branch
        run: |
          # Create a new gh-pages branch or reset it if it exists
          if git ls-remote --heads origin gh-pages | grep gh-pages; then
            git fetch origin gh-pages
            git checkout gh-pages
            git reset --hard origin/main
          else
            git checkout -b gh-pages
          fi
          
          # Remove everything except the docs directory
          find . -maxdepth 1 -not -path "./docs" -not -path "./.git" -not -path "." -exec rm -rf {} \;
          
          # Move docs content to root
          mv docs/* .
          rm -rf docs
          
          # Add and commit changes
          git add .
          git commit -m "Deploy documentation"
          
          # Push to gh-pages branch
          git push origin gh-pages --force
          
          # Return to original branch
          git checkout -
          
      - name: Verify deployment
        run: |
          echo "Documentation deployed to GitHub Pages"
          echo "If the documentation is not visible, please check the GitHub Pages settings in the repository" 