name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy_docs.yml'
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install pymdown-extensions
          pip install "mkdocstrings[python]"
          pip install -e .
      
      - name: Configure Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Create .nojekyll file
        run: |
          touch ./docs/.nojekyll
      
      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force
          
      - name: Verify deployment
        run: |
          echo "Documentation deployed to GitHub Pages"
          echo "If the documentation is not visible, please check the GitHub Pages settings in the repository" 