name: "Security Tests"
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow has been disabled"
