# DEPRECATED - This workflow is no longer used. See fresh_ci.yml instead.
# This file is kept for reference purposes only.
name: Deprecated Publish Package

on:
  workflow_dispatch:
    # This workflow can only be manually triggered now
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
        python -m pip install -e ".[dev,test]"
        
    - name: Run tests
      run: python -m pytest
        
    - name: Skip security check
      run: |
        echo "Skipping security checks temporarily"
        
    - name: Build package
      run: python -m build
      
    - name: Validate built package
      run: |
        # Check that version matches the tag
        VERSION=$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/^v//')
        echo "Release version from tag: $VERSION"
        PACKAGE_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
        echo "Package version in pyproject.toml: $PACKAGE_VERSION"
        
        if [ "$VERSION" != "$PACKAGE_VERSION" ]; then
          echo "ERROR: Version mismatch! Tag version ($VERSION) does not match package version ($PACKAGE_VERSION)"
          exit 1
        fi
        
        echo "Versions match! Proceeding with package validation..."
        twine check dist/*
      
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload dist/*