name: Security Checks

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  security-checks:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for some security scanners

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[security,test]"
          pip install pytest-github-actions-annotate-failures
          pip install semgrep
          pip install detect-secrets
          pip install pysa

      # Basic Security Checks
      - name: Run Bandit
        run: bandit -c pyproject.toml -r src/ -ll -v

      - name: Run Safety Check
        run: safety check --json > safety-report.json

      - name: Run pip-audit
        run: pip-audit --desc --format json > pip-audit-report.json

      - name: Run Ruff security checks
        run: ruff check . --select S,B --output-format=github

      # Advanced SAST
      - name: Run Semgrep Security Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/owasp-top-ten
            p/python
            p/jwt-security
            p/secrets
          output: semgrep-results.json
          
      - name: Run PySA (Python Static Analyzer)
        run: pysa analyze src/

      - name: Run detect-secrets
        run: detect-secrets scan > secrets-scan.json

      # Software Composition Analysis (SCA)
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'cylestio-monitor'
          path: '.'
          format: 'JSON'
          out: 'reports'

      - name: Run Snyk
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --all-projects --severity-threshold=low

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: low
          vulnerability-check: true
          license-check: true
          config-file: '.github/dependency-review-config.yml'

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
          queries: security-extended,security-and-quality
          config-file: .github/codeql/codeql-config.yml
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
          upload: true

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: GitGuardian scan
        if: ${{ env.GITGUARDIAN_API_KEY != '' }}
        uses: GitGuardian/ggshield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  security-report:
    needs: [security-checks, dependency-review, codeql, secret-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Generate Security Report
        run: |
          echo "# Security Scan Results" > security-report.md
          echo "## SAST Results" >> security-report.md
          cat semgrep-results.json >> security-report.md || echo "No semgrep results found" >> security-report.md
          echo "## Dependency Check Results" >> security-report.md
          cat reports/dependency-check-report.json >> security-report.md || echo "No dependency check results found" >> security-report.md
          echo "## Safety Check Results" >> security-report.md
          cat safety-report.json >> security-report.md || echo "No safety results found" >> security-report.md

      - name: Upload Security Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: security-report.md

env:
  TOKEN: ${{ secrets.MY_SECRET }}
  MY_VAR: value 